### ISSUE TITLE
SqsAutoConfiguration should register sqsReceiverEndpointFactory

### ISSUE THREAD

**Issue by hstruebe** [otto-de/synapse#26]
Currently sqsReceiverEndpointFactory is returning MessageQueueReceiverEndpointFactory as a conditional Bean which skips creation if already a MessageQueueReceiverEndpointFactory is registered. This is the case if the KinesisAutoConfiguration has created his Beans already. So they should eventually return SqsMessageQueueReceiverEndpoint directly, which leads to problems beacuse it is no functional interface.

**Comment by guidosteinacker1969** [comment]
Ist das noch so? Sollte eigentlich nicht so sein und ich kann das nicht nachvollziehen...
